//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp24
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> TournamentId { get; set; }
        public int FirstPlayerId { get; set; }
        public int SecondPlayerId { get; set; }
    
        public virtual Player FirstPlayer { get; set; }
        public virtual Tournaments Tournament { get; set; }
        public virtual Player SecondPlayer { get; set; }
    }
}
