//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp24
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Id { get; set; }
        public Nullable<int> Number { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public Nullable<int> DepartureTime { get; set; }
        public Nullable<int> ArrivalTime { get; set; }
        public Nullable<int> FlightNumber { get; set; }
        public string DeparturePlaces { get; set; }
        public string ArrivalsPlaces { get; set; }
    }
}
